In [2]:
import numpy as np
import pandas as pd
import os.path
from sklearn.metrics import roc_auc_score
import tqdm

# Santander Customer Transaction Prediction (KAGGLE)

Leer de que trata la competencia

https://www.kaggle.com/c/santander-customer-transaction-prediction/overview

# Bajada de Dataset
La siguiente celda baja el dataset y lo guarda en la carpeta /data.

Luego de ejecutarla debería tener los archivos train.csv y test.csv en esta carpeta

# Carpeta on dataset:
https://drive.google.com/drive/folders/19scmxZ64fe7mIneDwG21eF_QLn-8-S8j?usp=sharing

In [5]:
#Si quiero habilitar mi google drive descomentar
from google.colab import drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive


# Cargar datos de train

In [6]:
df_train = pd.read_csv('/content/gdrive/MyDrive/data/train.csv')
df_test = pd.read_csv('/content/gdrive/MyDrive/data/test.csv')

In [7]:
# Miramos las primeras 5 observaciones del dataset
df_train.head()

# TODO: Importar datos de test y asignarlos a la variable df_test desde la carpeta data/
# df_test  = 

ID_code  target    var_0   var_1  ...  var_196  var_197  var_198  var_199
0  train_0       0   8.9255 -6.7863  ...   7.8784   8.5635  12.7803  -1.0914
1  train_1       0  11.5006 -4.1473  ...   8.1267   8.7889  18.3560   1.9518
2  train_2       0   8.6093 -2.7457  ...  -6.5213   8.2675  14.7222   0.3965
3  train_3       0  11.0604 -2.1518  ...  -2.9275  10.2922  17.9697  -8.9996
4  train_4       0   9.8369 -1.4834  ...   3.9267   9.5031  17.9974  -8.8104

[5 rows x 202 columns]

In [10]:
print(pd.value_counts(df_train.target))

print(179902/(179902+ 20098))

0    179902
1     20098
Name: target, dtype: int64
0.89951


In [27]:
np.unique(np.array(df_train.target))

array([0, 1])

In [11]:
df_train.columns

Index(['ID_code', 'target', 'var_0', 'var_1', 'var_2', 'var_3', 'var_4',
       'var_5', 'var_6', 'var_7',
       ...
       'var_190', 'var_191', 'var_192', 'var_193', 'var_194', 'var_195',
       'var_196', 'var_197', 'var_198', 'var_199'],
      dtype='object', length=202)

Cuantas features (covariables, variable explicativa, variable independiente, variables exógenas) hay (dimensión de las observaciones, regresoras)? Que columna contiene la salida (variable dependiente, variable endógena)? Cuantas clases hay? Cuantas observaciones tiene train?

In [12]:
df_train.describe()

target          var_0  ...        var_198        var_199
count  200000.000000  200000.000000  ...  200000.000000  200000.000000
mean        0.100490      10.679914  ...      15.870720      -3.326537
std         0.300653       3.040051  ...       3.010945      10.438015
min         0.000000       0.408400  ...       6.299300     -38.852800
25%         0.000000       8.453850  ...      13.829700     -11.208475
50%         0.000000      10.524750  ...      15.934050      -2.819550
75%         0.000000      12.758200  ...      18.064725       4.836800
max         1.000000      20.315000  ...      26.079100      28.500700

[8 rows x 201 columns]

In [ ]:
# TODO: Inspeccionar test
# Puede ejecutar los métodos que crea necesarios. Recomendamos describe, columns, shape, head

Que columna esta en los datos de train pero no en los de test? Cuantas observaciones de test hay?

# Dividir data en Train y Val

In [43]:
N_train = 160_000
X_train = df_train.drop(columns=['ID_code', 'target']).values[:N_train]
X_val = df_train.drop(columns=['ID_code', 'target']).values[N_train:]
y_train = df_train['target'].values[:N_train]
y_val = df_train['target'].values[N_train:]

def normal(serie): 
  return (serie-np.mean(serie))/np.std(serie)

X_train=normal(df_train.drop(columns=['ID_code', 'target']).values[:N_train])
X_val=normal(df_train.drop(columns=['ID_code', 'target']).values[N_train:])
#y_train=normal( df_train['target'].values[:N_train])
#y_val=normal(df_train['target'].values[N_train:])

In [38]:
X_train

array([[ 0.22332347, -1.40257448,  0.53197068, ...,  0.18586277,
         0.62222821, -0.81325141],
       [ 0.48980152, -1.12948389,  0.73383419, ...,  0.20918775,
         1.19921615, -0.49833315],
       [ 0.19060227, -0.98444267,  0.54981108, ...,  0.15523192,
         0.82318107, -0.65927964],
       ...,
       [ 0.28809323, -0.74405259,  0.12877142, ...,  0.31944846,
         1.31757955,  0.00877299],
       [ 0.13550814, -0.96776128,  0.51894222, ...,  0.27781741,
         0.57519536,  0.60154203],
       [ 0.5119261 , -0.9227153 ,  0.21913243, ...,  0.11652943,
         0.95966428, -0.61376799]])

# Regresión logística

In [44]:
from sklearn.linear_model import LogisticRegression

In [45]:
model = LogisticRegression(solver='lbfgs', max_iter=100)

In [46]:
%time model.fit(X_train, y_train)

CPU times: user 13.6 s, sys: 2.35 s, total: 16 s
Wall time: 8.33 s


/usr/local/lib/python3.7/dist-packages/sklearn/linear_model/_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

A que se debe el warning no termina de convergence?

In [47]:
acc = model.score(X_train, y_train)
auc = roc_auc_score(y_train, model.predict_proba(X_train)[:,1])
print(auc)
print(acc)

0.8514768336351206
0.912675


In [48]:
print(roc_auc_score(y_val, model.predict_proba(X_val)[:,1]))
print(model.score(X_val, y_val))

0.8532351658168906
0.911975


cuantos parámetros aprendio el modelo?

# Normalizar los datos

In [50]:
means = X_train.mean(axis=0)
stds = X_train.std(axis=0)

In [51]:
X_train_normalized = (X_train - means)/stds
X_val_normalized = (X_val - means)/stds

In [52]:
model_2 = LogisticRegression(solver='lbfgs')
%time model_2.fit(X_train_normalized, y_train)

CPU times: user 1.35 s, sys: 227 ms, total: 1.58 s
Wall time: 886 ms


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [53]:
print(model_2.score(X_train_normalized, y_train))
print(roc_auc_score(y_train, model_2.predict_proba(X_train_normalized)[:,1]))

0.91440625
0.8606427353156717


In [54]:
print(model_2.score(X_val_normalized, y_val))
print(roc_auc_score(y_val, model_2.predict_proba(X_val_normalized)[:,1]))

0.914475
0.8629075884886785


In [56]:
model_2.coef_.shape

(1, 200)

In [ ]:
# Ordenamos el valor absoluto de los parámetros de mayor a menor
# Coeficientes ordenados en función de su de mayor importancia
np.argsort(np.abs(model_2.coef_))[0][::-1]

array([ 81, 139,   6,  12,  53, 110,  76,  99, 146, 174,  26,  21,  22,
        80, 190, 166, 165, 198,  13,  34, 169,  44,   2, 148,   0,  40,
       133, 179, 170,  78,  94,   1, 184, 109,  33, 115,  92,  67, 149,
       108, 191, 122, 173, 154,  18,  86, 192, 118, 107, 121, 147,  95,
         9,  75,  35, 164, 177, 197, 172,  36, 127,  89, 123, 155,  91,
       188,  56,  87,  71,  48,   5,  93, 162, 106, 157, 130, 141, 145,
        24, 151,  32, 167, 163, 150, 186, 119,  49,  31, 180,  23, 111,
       195,  90, 131, 125, 137, 114, 199,  43, 116, 135,  52,  58, 128,
        70, 104, 175, 112, 132, 105,  11, 196,  85,  82, 194,  51,  28,
       142,  83,  66, 134, 144, 138,  74,  45, 156,  77,  55,  97, 140,
        20,  54, 193,  57,  88, 178,   8, 102, 113,  62,  15, 143, 159,
       187, 181, 171,  63,  72,  64,  50,  59, 120, 168, 182, 101,  25,
        68,   3,  65, 152,   4,  84,  37,  42, 176,  61, 129,  19, 189,
        69,  47,  60,  16,  27,  29,  79,  73, 158,  96, 160,  4

In [57]:
# Parámetros menores a cero
negative_indexes = np.where(model.coef_<0)[1]
negative_indexes

array([  9,  10,  12,  13,  14,  17,  20,  21,  23,  27,  28,  30,  31,
        33,  34,  36,  38,  39,  41,  42,  43,  44,  45,  50,  54,  56,
        57,  58,  59,  63,  64,  68,  71,  72,  73,  75,  76,  77,  80,
        81,  83,  85,  86,  87,  88,  92,  93,  98, 101, 102, 103, 104,
       107, 109, 113, 114, 115, 116, 120, 121, 122, 123, 127, 129, 131,
       132, 136, 139, 141, 142, 143, 146, 148, 149, 150, 152, 153, 154,
       156, 158, 160, 161, 165, 166, 169, 172, 174, 177, 178, 182, 183,
       186, 188, 192, 193, 194, 197, 198])

In [ ]:
# Parámetros mayores a cero
positive_indexes = np.where(model.coef_>0)[1]
positive_indexes

array([  0,   1,   2,   3,   4,   5,   6,   8,  11,  15,  16,  18,  19,
        22,  24,  25,  26,  29,  30,  32,  35,  37,  38,  40,  46,  47,
        48,  49,  51,  52,  53,  55,  60,  61,  62,  65,  66,  67,  68,
        69,  70,  71,  74,  78,  79,  82,  84,  89,  90,  91,  94,  95,
        96,  97,  99, 100, 103, 105, 106, 108, 110, 111, 112, 117, 118,
       119, 124, 125, 126, 128, 130, 133, 134, 135, 137, 138, 140, 144,
       145, 147, 151, 155, 157, 159, 161, 162, 163, 164, 167, 168, 170,
       171, 173, 175, 176, 179, 180, 181, 184, 187, 189, 190, 191, 195,
       196, 199])

In [ ]:
len(negative_indexes)/len(positive_indexes)

0.8867924528301887

Notar que hay algunos parámetros mayores a cero y otros menores a cero. Como contribuyen en función de su signo?

In [59]:
# Ordenados de menor a mayor
np.argsort(model_2.coef_)[0]

array([ 81, 139,  12,  76, 146, 174,  21,  80, 166, 165, 198,  13,  34,
       169,  44, 148, 109,  33, 115,  92, 149, 108, 122, 154,  86, 192,
       107, 121,   9,  75, 177, 197, 172,  36, 127, 123, 188,  56,  87,
        93, 141, 150, 186,  31,  23, 131, 114,  43, 116,  58, 104, 132,
        85, 194,  28, 142,  83,  45, 156,  77,  20,  54, 193,  57,  88,
       178, 102, 113, 143,  63,  72,  64,  50,  59, 120, 182, 101,  68,
       152,  42, 129,  27,  73, 158, 160,  98,  14, 153,  39, 136, 183,
        41, 103,  10,   7, 185,  38,  17,  30, 161, 100, 117, 126, 124,
        46,  96,  79,  29,  16,  60,  47,  69, 189,  19,  61, 176,  37,
        84,   4,  65,   3,  25, 168, 171, 181, 187, 159,  15,  62,   8,
       140,  97,  55,  74, 138, 144, 134,  66,  51,  82, 196,  11, 105,
       112, 175,  70, 128,  52, 135, 199, 137, 125,  90, 195, 111, 180,
        49, 119, 163, 167,  32, 151,  24, 145, 130, 157, 106, 162,   5,
        48,  71,  91, 155,  89, 164,  35,  95, 147, 118,  18, 17

In [ ]:
# Ordenados de mayor a menor
np.argsort(model_2.coef_)[0][::-1]

array([  6,  53, 110,  99,  26,  22, 190,   2,   0,  40, 133, 179, 170,
        78,  94,   1, 184,  67, 191, 173,  18, 118, 147,  95,  35, 164,
        89, 155,  91,  71,  48,   5, 162, 106, 157, 130, 145,  24, 151,
        32, 167, 163, 119,  49, 180, 111, 195,  90, 125, 137, 199, 135,
        52, 128,  70, 175, 112, 105,  11, 196,  82,  51,  66, 134, 144,
       138,  74,  55,  97, 140,   8,  62,  15, 159, 187, 181, 171, 168,
        25,   3,  65,   4,  84,  37, 176,  61,  19, 189,  69,  47,  60,
        16,  29,  79,  96,  46, 124, 126, 117, 100, 161,  30,  17,  38,
       185,   7,  10, 103,  41, 183, 136,  39, 153,  14,  98, 160, 158,
        73,  27, 129,  42, 152,  68, 101, 182, 120,  59,  50,  64,  72,
        63, 143, 113, 102, 178,  88,  57, 193,  54,  20,  77, 156,  45,
        83, 142,  28, 194,  85, 132, 104,  58, 116,  43, 114, 131,  23,
        31, 186, 150, 141,  93,  87,  56, 188, 123, 127,  36, 172, 197,
       177,  75,   9, 121, 107, 192,  86, 154, 122, 108, 149,  9

In [ ]:
# Calculamos correlación de cada variable con la salida
correlations = []
for i in range(200):
    correlations.append(np.corrcoef(y_train, X_train_normalized[:,i])[1,0])

In [ ]:
np.argsort(np.abs(correlations))[::-1]

array([ 81, 139,  12, 110,   6,  26,  53, 146, 174,  76,  99,  80, 166,
        22, 165,  21, 190, 148,   2,  13,  34, 133,   0, 198, 169, 109,
       179,  44,  40,   1, 115, 149, 170, 184,  78,  94,  92, 108,  67,
       191,  33,  18, 154, 173,  86, 122, 192, 147, 118,   9, 121,  75,
        95, 164, 123,  35,  91,  36, 172, 127, 107, 155,  89, 177, 197,
        56,  93, 188,  87,  71, 162,  48, 157, 106, 141, 145,   5,  32,
       163, 131, 167, 186, 119,  49,  24, 151, 130,  90, 111, 135, 180,
       125,  43,  51, 114, 195, 199,  52,  23, 150,  31, 116,  85,  70,
       137, 105, 128, 104,  58, 112, 196, 132,  11,  28, 175,  66,  82,
       194, 156,  83, 142,  45, 144,  88,  74, 178, 138,  77,   8,  97,
       134,  20,  55, 193,  54,  15, 102,  57, 159, 140, 171,  62, 113,
       187,  63, 143,  64,  25, 181,  50, 120, 168,  59,   3,  72,  65,
        68,  84, 101,  19,   4,  37,  61,  69, 189, 152, 182,  42,  16,
       129, 176,  47,  79, 153,  14, 183,  46, 160,  73,  60,  9

# Feature engineering

In [60]:
# Agregamos 200 columnas con el cuadrado de cada columna normaliado a train
X_train_sq = X_train_normalized**2
means_sq = X_train_sq.mean(axis=0)
stds_sq = X_train_sq.std(axis=0)
X_train_FE = np.append(X_train_normalized, (X_train_sq - means_sq)/stds_sq, axis=1)

# Agregamos el cuadrado a validación normalizando con la media y std obtenida en train
X_val_sq = X_val_normalized**2
X_val_FE = np.append(X_val_normalized, (X_val_normalized**2-means_sq)/stds_sq, axis=1)

In [61]:
model_3 = LogisticRegression(solver='lbfgs')
%time model_3.fit(X_train_FE, y_train)

CPU times: user 2.53 s, sys: 263 ms, total: 2.8 s
Wall time: 1.57 s


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [62]:
print(model_3.score(X_train_FE, y_train))
print(roc_auc_score(y_train, model_3.predict_proba(X_train_FE)[:,1]))

0.9218625
0.8910807326950416


In [ ]:
print(model_3.score(X_val_FE, y_val))
print(roc_auc_score(y_val, model_3.predict_proba(X_val_FE)[:,1]))

0.9221
0.8927208962331821


In [ ]:
# Coeficientes ordenados en función de su de mayor importancia
np.argsort(np.abs(model_3.coef_))[0][::-1]

array([139,  81,   6,  53,  12,  21,  76, 174, 110,  34, 146,  26, 169,
        99, 165, 281,  22, 166, 190,  78,  33,  40,  13, 170, 149,  80,
       148, 184,  94, 109, 133, 192,  92, 122, 115,  67, 121, 198,   0,
         1, 173, 179,   2, 212,  18, 118, 108, 253, 398, 107, 191, 172,
       177,  44, 154, 310, 164,  35, 197, 226, 188,  36, 339, 299,  75,
       147, 244,   9, 280,  86,  87, 366,  95,  89,  48, 390, 127,  91,
       222, 309,  71, 346, 155, 202,   5, 323, 374, 379,  56, 145, 106,
       162, 123, 206, 221,  32, 186, 141, 200, 150, 348, 151,  31, 365,
       199,  49, 130, 240,  23, 278, 167, 157,  24, 333,  90, 276,  93,
       111, 119, 354, 137, 364, 195, 286, 363, 128, 112, 180, 380,  52,
       104, 114,  58, 131,  70, 355, 116, 125, 135, 295, 370, 233, 391,
       292, 201,  43, 275, 175, 196, 293, 357, 388, 294,  85, 163, 213,
       347,  82, 308, 142, 132,  28, 105,  11, 319, 234, 194, 291,  74,
       205,  97,  77, 140, 315,  45, 322,  20, 369,  55, 267, 25

# Independecia

In [ ]:
accs = []
aucs = []
val_predictions = np.zeros((len(X_val_normalized), 200))
train_predictions = np.zeros((len(X_train_normalized), 200))
for i in tqdm.tqdm(range(200)):
    model_ind = LogisticRegression(solver='lbfgs')
    X_one_train = X_train_normalized[:,i].reshape(-1,1)
    # X_one_train = np.array([X_train_normalized[:,i], X_train_normalized[:,i]**2]).T
    model_ind.fit(X_one_train, y_train)
    X_one_val = X_val_normalized[:,i].reshape(-1,1)
    # X_one_val = np.array([X_val_normalized[:,i], X_val_normalized[:,i]**2]).T
    train_predictions[:, i] = model_ind.predict_proba(X_one_train)[:,1]
    val_predictions[:, i] = model_ind.predict_proba(X_one_val)[:,1]
    acc = model_ind.score(X_one_val, y_val)
    auc = roc_auc_score(y_val, val_predictions[:, i])
    accs.append(acc)
    aucs.append(auc)

100%|██████████| 200/200 [00:20<00:00,  8.22it/s]


In [ ]:
roc_auc_score(y_train, train_predictions.sum(axis=1)) 

0.8692585548756987

In [ ]:
roc_auc_score(y_val, val_predictions.sum(axis=1)) 
# 0.8729094090424484

0.8729094090424484